language: node_js
env:
  - NODE_ENV=production
node_js:
  - "8"
sudo: false
os:
  - linux
cache:
  directories:
    - tests/elm-stuff/build-artifacts
install:
  - npm install -g elm elm-test
  - elm-package install --yes
  - npm install
script:
  - elm test
