module FsmState exposing (..)


type FsmState
    = Start
    | Statement
    | SpaceTerm
    | WordTerm
    | KeywordTerm
    | Value
    | MultiQuotedWord
    | StartQuoteTerm
    | EndQuoteTerm
    | Criteria
    | Criterion
    | Conjunction
    | Operator
    | OperatorGroup
    | OperatorGroupOr
    | OperatorGroupAnd
    | AndTerm
    | OrTerm
    | NorTerm
    | NotTerm
    | IsTerm
    | IsOperator
    | IsSubOperator
    | EitherTerm
    | EitherOrOperator
    | NeitherTerm
    | NeitherNorOperator
    | UnknownKeywordTerm
    | InTerm
    | InOperator
    | InValue
    | OpenParenthesisTerm
    | CloseParenthesisTerm
    | CommaTerm
    | InRepeatValue
